# install ha proxy
- name: wait 15 seconds for apt lock
  wait_for:
    timeout: 15
  delegate_to: localhost

- name: install ha proxy
  apt:
    pkg: haproxy
    state: latest
    update_cache: yes
  become: true

- name: configure ha proxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

- name: restart haproxy
  service:
    name: "haproxy"
    state: restarted