apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx
  name: nginx-deploy-main
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx-main
  template:
    metadata:
      labels:
        run: nginx-main
    spec:
      containers:
      - image: nginx
        name: nginx

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx
  name: nginx-deploy-main
  namespace: default
spec:
  selector:
    run: nginx-main
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: letsencrypt-staging
  name: nginx-k8s
spec:
  tls:
  - hosts: 
    - nginx-k8s.ombada.tech
    secretName: nginx-k8s-ombada-tech-tls
  ingressClassName: nginx
  rules:
  - host: nginx-k8s.ombada.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-deploy-main
            port: 
              number: 80